### ISSUE TITLE
Prototype: Figma prototype

### ISSUE THREAD

**Issue by AbraaoAlves** [dcTeam7/students-dashboard#1]
##  Feature

We need a prototype with Figma or another similar tool to express concepts about this project.

### Concepts

A dashboard to visualize a list of students, showing their photos and links for study tools (duolingo, freecodecamp and github).

**Comment by AbraaoAlves** [comment]
Just an image idea with some information: 
![image](https://user-images.githubusercontent.com/608731/194288613-80d4f200-4d95-4f6b-8f71-6774e05b939e.png)

Notice that the image items have bullet icons.

**Comment by joellacerda** [comment]
Me, @Deborahhm and @gabrielapcustodio have done the dashboard mockup on Figma and the results look like this:

![Captura de tela 2022-10-06 080432](https://user-images.githubusercontent.com/98550669/194297329-14ed74ab-5ccd-41af-a420-0c89b759d541.png)

We want to add these features:

- Profile picture
- Links to the GitHub, freeCodeCamp and Duolingo profiles on the image icons
- Points for activities done on those sites
- (Optional: search bar to search by student name)

**Comment by joellacerdev** [comment]
[Link to the Figma project.](https://www.figma.com/file/Il5CIyGbqczvhNqjPVPoEQ/Dashboard?node-id=0%3A1)

**Comment by joellacerda** [comment]
@AbraaoAlves we have done some changes to the project (specially Caio, can you add him to our team?). The current prototype is looking really good! Also, here's the [link](https://www.figma.com/file/Il5CIyGbqczvhNqjPVPoEQ/Dashboard?node-id=0%3A1) to our Figma project.

<img width="269" alt="image" src="https://user-images.githubusercontent.com/98550669/194614342-de921962-eb34-49ef-a022-42106be2fe2c.png">
